/home/augusto/miniconda3/envs/sr/lib/python3.8/site-packages/trl/trainer/ppo_trainer.py:239: UserWarning: No dataset is provided. Make sure to set config.batch_size to the correct value before training.
  warnings.warn(
avaliation.py:114: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  query_tensors = list(torch.tensor(query_tensors))
Index(['type', 'name', 'expression'], dtype='object')
Working with expression:  2 * x[0] + 3
<lambdifygenerated-10>:2: RuntimeWarning: invalid value encountered in power
  return (1/4)*x**(3/2)
Traceback (most recent call last):
  File "avaliation.py", line 132, in <module>
    exprs, rewards, r2 = reward_pipeline(response_tensors, data)
  File "avaliation.py", line 36, in reward_pipeline
    exprs = [Expression(prefix.strip().split(" "), data) for prefix in prefixes]
  File "avaliation.py", line 36, in <listcomp>
    exprs = [Expression(prefix.strip().split(" "), data) for prefix in prefixes]
  File "/home/augusto/symbolic/Expression.py", line 28, in __init__
    self.r2 = r2_score(data.y, self.y_pred)
  File "/home/augusto/miniconda3/envs/sr/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/augusto/miniconda3/envs/sr/lib/python3.8/site-packages/sklearn/metrics/_regression.py", line 989, in r2_score
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "/home/augusto/miniconda3/envs/sr/lib/python3.8/site-packages/sklearn/metrics/_regression.py", line 101, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "/home/augusto/miniconda3/envs/sr/lib/python3.8/site-packages/sklearn/utils/validation.py", line 957, in check_array
    _assert_all_finite(
  File "/home/augusto/miniconda3/envs/sr/lib/python3.8/site-packages/sklearn/utils/validation.py", line 122, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/home/augusto/miniconda3/envs/sr/lib/python3.8/site-packages/sklearn/utils/validation.py", line 171, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.
None 0.0000
x**4 + 2*x 0.0000
None 0.0000
x**2/sin(1) 0.0207
4*x*asinh(x) 0.0906
None 0.0000
2*tan(x) 0.4731
None 0.0000
x**2 - 3*x 0.0245
x*(x - 8) 0.0244
None 0.0000
None 0.0000
2*x + cosh(x) 0.0000
None 0.0000
6*x + 2 0.3333
2*x**2 + 5*x 0.0124